### ISSUE TITLE
usage ?

### ISSUE THREAD

**Issue by gedw99** [livebud/tailwind#2]
Normally  i have to do this..

```sh
tailwindcss -o ./public/styles.css --minify --watch
```

So then how to do this with this package ?
```sh
tailwind -o ./public/styles.css --minify --watch
```

**Comment by matthewmueller** [comment]
This package is more tailored to programmatic usage. It does come with a CLI, but it's just a simple example. To do what you suggested, you can create your own CLI that uses the library.
